version: '3'

volumes:
  database: {}

services:
  database:
    image: postgres:11.6
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: flashimages
      PGUSER: docker
      PGPASSWORD: docker
    volumes:
      - 'database:/var/lib/postgresql/data'

  api:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - database
    volumes:
      - './api:/var/www:cached'
    command: npm run start:dev

  client:
    image: node:14.3
    working_dir: '/var/www'
    depends_on:
      - api
    volumes:
      - './client:/var/www:cached'
    ports:
      - 5000:5000
      - 10000:10000
    command: npm run dev

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - 'client'
      - 'api'
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
